services:
    postgres:
        image: postgres
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=${DATABASE_HOST}
            - POSTGRES_PORT=${DATABASE_PORT}
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres:
